name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Log in to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t jhlp/fc-nestjs-gateway:latest -t jhlp/fc-nestjs-gateway:${{github.sha}} -f ./apps/gateway/Dockerfile --target production --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t jhlp/fc-nestjs-notification:latest -t jhlp/fc-nestjs-notification:${{github.sha}} -f ./apps/notification/Dockerfile --target production --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t jhlp/fc-nestjs-order:latest -t jhlp/fc-nestjs-order:${{github.sha}} -f ./apps/order/Dockerfile --target production --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t jhlp/fc-nestjs-payment:latest -t jhlp/fc-nestjs-payment:${{github.sha}} -f ./apps/payment/Dockerfile --target production --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t jhlp/fc-nestjs-product:latest -t jhlp/fc-nestjs-product:${{github.sha}} -f ./apps/product/Dockerfile --target production --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t jhlp/fc-nestjs-user:latest -t jhlp/fc-nestjs-user:${{github.sha}} -f ./apps/user/Dockerfile --target production --push .